spring:
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:dcbapp'
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
server.port: 8000
